### ISSUE TITLE
Upsert into pgvector Postgres Vector store is buggy

### ISSUE THREAD

**Issue by ajerni** [FlowiseAI/Flowise#5611]
### Describe the bug

Data Store upsert into Postgres seems to be a bit buggy... somtimes it works, but most of the time I get sever error:
```
Status: 500
Error: documentStoreServices.insertIntoVectorStoreMiddleware - Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - Error: Error inserting: MB301 | MXR
®
 Bass Synth  3
KNOBVOICESHAPE
```

### To Reproduce

try to use Document Store with Postgres vector database.

### Expected behavior

not error 500

### Use Method

None

### Operating System

None

### Browser

None

**Comment by m3svcs** [comment]
Upserting to PGVector database on 3.0.12 is no problem for me on the GUI but the API failed.  The previously working API version is now asking for password although I supplied Postgres credential in the JSON, it was worked on previous versions before.  This is the error message.

<img width="672" height="317" alt="Image" src="https://github.com/user-attachments/assets/4c441286-0b5c-403e-8dc3-6236bc446daf" />

Thank you very much.

M3

**Comment by wagnerloch** [comment]
I've been experiencing the same issue where the current version fails to auto-create tables during PostgreSQL upserts, triggering a 500 Internal Server Error.

After some testing, I found that rolling back to version 3.0.5 resolves the issue completely with the exact same environment configurations. It seems there is a regression in the schema synchronization logic in the latest releases.

If you are facing this in a production environment, I recommend pinning your docker image to a stable previous version until a formal fix is merged:

`image: flowiseai/flowise:3.0.5`

Hope this helps anyone struggling with broken flows!

**Comment by Bielbcs** [comment]
I was facing the exact same issue with the 500 error on upsert. Following @wagnerloch advice to rollback to version 3.0.5 solved it for me as well. Thanks for the workaround!

**Comment by m3svcs** [comment]
Hi guys

Thanks for the 3.0.5 tip, I knew 3.0.5 will definitely work but I'd very much like the way 3.0.12 handles the document management.  In short, it does housekeeping of documents perfectly.  I badly need 3.0.12 because I have 400,000+ documents to upsert.

**Comment by m3svcs** [comment]
Hi guys

Updating to 3.0.13 still doesn't resolve the Upsert API error.  May need to wait for the fix in the next update.  Delete Doc API is also not working anymore.

Thank you.

**Comment by prd-hoang-doan** [comment]
Hi @ajerni , I tried to reproduce your issue at the [test case](https://github.com/FlowiseAI/Flowise/pull/5755/changes#diff-3b09a36e3115043efcee9374180e11c7f799be6e0d0abe4b0b7e699abaedca91R133-R143). Could you check the document to have the similar text in the test case?
I created the pull request to enhance the current sanitize documents function to avoid this.

**Comment by m3svcs** [comment]
> Hi guys
> 
> Updating to 3.0.13 still doesn't resolve the Upsert API error. May need to wait for the fix in the next update. Delete Doc API is also not working anymore.
> 
> Thank you.

Hi guys, updating to 3.1.0 sill doesn't address the Upsert API error. :-(

I might have to downgrade to 3.0.5 to get the API working again.

Thank you,

**Comment by prd-hoang-doan** [comment]
@m3svcs The pull request to sanitize the document is not merged yet, I saw your error image and found that it seems not come from sanitization problem (like `MB301 | MXR\u00AE\n Bass Synth\u00AD 3\x0CKNOBVOICESHAPE`). If your document is not credential or have any privacy, you can upload here so I can re-test with your documents to make sure the pull request is cover all existing use cases.

**Comment by m3svcs** [comment]
Thank you, prd-hoang-doan, for your reply.

I am using the API request that worked in 3.0.5.
Request:

```
------WebKitFormBoundaryAIisForAllWhoIuvaAI

Content-Disposition: form-data; name="files"; filename*=UTF-8''Jesus%20in%20Islam%2Etxt
Content-Type: application/octet-stream

In Islam, Jesus (Arabic: عِيسَى ٱبْنُ مَرْيَمَ, romanized: ʿĪsā ibn Maryam, lit. 'Jesus, son of Mary') is believed to be the penultimate prophet and messenger of God and the Messiah sent to guide the Children of Israel (Banī Isra'īl) with a book called the Injīl (Evangel or Gospel).

In the Quran, Jesus is described as the Messiah (al-Masīḥ), born of a virgin, performing miracles, accompanied by his disciples, and rejected by the Jewish religious establishment; in contrast to the traditional Christian narrative, however, he is stated to have not been crucified, died on the cross, nor resurrected, rather, he is depicted as having been miraculously saved by God and ascending into heaven. The Quran places Jesus among the greatest prophets and mentions him with various titles. The prophethood of Jesus is preceded by that of Yahya (John) and succeeded by Muhammad, the latter of whom Jesus is reported in the Quran to have prophesied by using the name Ahmad.

Christians view Jesus Christ as God incarnate, the Son of God in human flesh, but the Quran denies the divinity of Jesus and his status as Son of God in several verses, and also insinuates that Jesus Christ did not claim to be personally God nor the Son of God. Islam teaches that Jesus' original message was altered (taḥrīf) after his being raised alive. The monotheism (tawḥīd) of Jesus is emphasized in the Quran. Like all prophets in Islam, Jesus is also called a Muslim (lit. submitter [to God]), as he preached that his followers should adopt the 'straight path' (Ṣirāṭ al-Mustaqīm). Jesus is attributed with a vast number of miracles in Islamic tradition.

In their views of Islamic eschatology, mainstream Muslims believe Jesus will return in the Second Coming to kill the Al-Masih ad-Dajjal ('The False Messiah'), after which with the ancient tribe Gog and Magog (Yaʾjūj Maʾjūj) would disperse. After God gets rid of them, Jesus would rule the world, establish peace and justice, die a natural death and then be buried alongside Muhammad at the fourth reserved tomb of the Green Dome in Medina.

The place where Jesus is believed to return, the Umayyad Mosque in Damascus, is highly esteemed by Muslims as the fourth holiest site of Islam. Jesus Christ is widely venerated in Sufism, with numerous ascetic and mystic literature written and recited about the most important historical Jewish Christian-Islamic prophet-messenger to these Abrahamic faith
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="loader"
Content-Type: application/json

{"name": "textFile","config": {"txtFile":"Jesus in Islam.txt" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="splitter"
Content-Type: application/json

{"name": "recursiveCharacterTextSplitter", "config": {"chunkSize": 1000, "chunkOverlap": 200 } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="embedding"
Content-Type: application/json

{"name": "ollamaEmbedding", "config": { "baseUrl": "http://localhost:11434", "modelName": "nomic-embed-text:latest" } }

------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="vectorStore"
Content-Type: application/json

{ "name": "postgres", "config": { "connectCredentials": "Postgres", "host": "localhost", "database": "flowise", "port": 5432, "tableName": "documents", "distanceStrategy": "Cosine", "topK": 4, "contentColumnName": "pageContent" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="recordManager"
Content-Type: application/json

{ "name": "postgresRecordManager", "config": { "connectCredentials": "Postgres", "host": "localhost", "database": "flowise", "port": 5432, "tableName": "upsertion_records", "cleanup": "", "sourceIdKey": "source" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI--
```

Reponse:
`{"statusCode":500,"success":false,"message":"Error: documentStoreServices.upsertDocStoreMiddleware - MIME type \"application/octet-stream\" is not supported or does not have a valid file extension mapping","stack":{}}`

Thank you for your attention.

m3svcs

**Comment by m3svcs** [comment]
Hi, prd-hoang-doan, I referred to the below for my API construction:
<img width="3840" height="2060" alt="Image" src="https://github.com/user-attachments/assets/a8c74efc-9fb6-405c-85ae-0741b2df7816" />

Thank you very much.

m3svcs

**Comment by prd-hoang-doan** [comment]
@m3svcs Thank you for providing a detailed issue. I found that your issue don't related to the sanitization with special characters (MB301 | MXR®), but it's related to the MIME type of your files.

There are pull requests to fix security issues. You can find it at #5596 

```
------WebKitFormBoundaryAIisForAllWhoIuvaAI

Content-Disposition: form-data; name="files"; filename*=UTF-8''Jesus%20in%20Islam%2Etxt
Content-Type: application/octet-stream     <--- ISSUE HERE

In Islam, Jesus (Arabic: عِيسَى ٱبْنُ مَرْيَمَ, romanized: ʿĪsā ibn Maryam, lit. 'Jesus, son of Mary')
```

You can fix it by changing the right content-type.
```
------WebKitFormBoundaryAIisForAllWhoIuvaAI

Content-Disposition: form-data; name="files"; filename*=UTF-8''Jesus%20in%20Islam%2Etxt
Content-Type: multipart/form-data     <--- FIX

In Islam, Jesus (Arabic: عِيسَى ٱبْنُ مَرْيَمَ, romanized: ʿĪsā ibn Maryam, lit. 'Jesus, son of Mary')
```

I tested the API with your file on my local machine, the content is valid.

<img width="1081" height="630" alt="Image" src="https://github.com/user-attachments/assets/652127db-879a-4671-9d04-bdca96f66390" />

**Comment by m3svcs** [comment]
@prd-hoang-doan, thank you for your prompt reply.

 I still got the same upsert error after changing `application/octet-stream` to `multi-part/form-data`.

Request:
```
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="files"; filename*=UTF-8''Jesus%20in%20Islam%2Etxt
Content-Type: multipart/form-data

In Islam, Jesus (Arabic: عِيسَى ٱبْنُ مَرْيَمَ, romanized: ʿĪsā ibn Maryam, lit. 'Jesus, son of Mary') is believed to be the penultimate prophet and messenger of God and the Messiah sent to guide the Children of Israel (Banī Isra'īl) with a book called the Injīl (Evangel or Gospel).

In the Quran, Jesus is described as the Messiah (al-Masīḥ), born of a virgin, performing miracles, accompanied by his disciples, and rejected by the Jewish religious establishment; in contrast to the traditional Christian narrative, however, he is stated to have not been crucified, died on the cross, nor resurrected, rather, he is depicted as having been miraculously saved by God and ascending into heaven. The Quran places Jesus among the greatest prophets and mentions him with various titles. The prophethood of Jesus is preceded by that of Yahya (John) and succeeded by Muhammad, the latter of whom Jesus is reported in the Quran to have prophesied by using the name Ahmad.

Christians view Jesus Christ as God incarnate, the Son of God in human flesh, but the Quran denies the divinity of Jesus and his status as Son of God in several verses, and also insinuates that Jesus Christ did not claim to be personally God nor the Son of God. Islam teaches that Jesus' original message was altered (taḥrīf) after his being raised alive. The monotheism (tawḥīd) of Jesus is emphasized in the Quran. Like all prophets in Islam, Jesus is also called a Muslim (lit. submitter [to God]), as he preached that his followers should adopt the 'straight path' (Ṣirāṭ al-Mustaqīm). Jesus is attributed with a vast number of miracles in Islamic tradition.

In their views of Islamic eschatology, mainstream Muslims believe Jesus will return in the Second Coming to kill the Al-Masih ad-Dajjal ('The False Messiah'), after which with the ancient tribe Gog and Magog (Yaʾjūj Maʾjūj) would disperse. After God gets rid of them, Jesus would rule the world, establish peace and justice, die a natural death and then be buried alongside Muhammad at the fourth reserved tomb of the Green Dome in Medina.

The place where Jesus is believed to return, the Umayyad Mosque in Damascus, is highly esteemed by Muslims as the fourth holiest site of Islam. Jesus Christ is widely venerated in Sufism, with numerous ascetic and mystic literature written and recited about the most important historical Jewish Christian-Islamic prophet-messenger to these Abrahamic faith
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="loader"
Content-Type: application/json

{"name": "textFile","config": {"txtFile":"Jesus in Islam.txt" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="splitter"
Content-Type: application/json

{"name": "recursiveCharacterTextSplitter", "config": {"chunkSize": 1000, "chunkOverlap": 200 } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="embedding"
Content-Type: application/json

{"name": "ollamaEmbedding", "config": { "baseUrl": "http://localhost:11434", "modelName": "nomic-embed-text:latest" } }

------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="vectorStore"
Content-Type: application/json

{ "name": "postgres", "config": { "connectCredentials": "Postgres", "host": "localhost", "database": "flowise", "port": 5432, "tableName": "documents", "distanceStrategy": "Cosine", "topK": 4, "contentColumnName": "pageContent" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="recordManager"
Content-Type: application/json

{ "name": "postgresRecordManager", "config": { "connectCredentials": "Postgres", "host": "localhost", "database": "flowise", "port": 5432, "tableName": "upsertion_records", "cleanup": "", "sourceIdKey": "source" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI--
```

Response:
```
{"statusCode":500,"success":false,"message":"Error: documentStoreServices.upsertDocStoreMiddleware - MIME type \"multipart/form-data\" is not supported or does not have a valid file extension mapping","stack":{}}
```

This is the Flowise version I'm using `flowise/3.1.0 win32-x64 node-v20.20.1`:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e2e68798-a6e7-4908-bafa-a2a30928164d" />

Thank you very much.

**Comment by prd-hoang-doan** [comment]
@m3svcs Could you provide more context how you call the API `upsert`? For example, you call it from another application using python/javascript script, or Flowise UI, or curl, or using Postman like me. 
It's better to help me debug the issue. 
The error response still come from the validation on the mentioned PR above. 
During that time, you can try it again by changing the content-type of the file.

```
------WebKitFormBoundaryAIisForAllWhoIuvaAI

Content-Disposition: form-data; name="files"; filename*=UTF-8''Jesus%20in%20Islam%2Etxt
Content-Type: text/plain     <--- FIX

In Islam, Jesus (Arabic: عِيسَى ٱبْنُ مَرْيَمَ, romanized: ʿĪsā ibn Maryam, lit. 'Jesus, son of Mary')
```

Expected logs should be like:

<img width="776" height="482" alt="Image" src="https://github.com/user-attachments/assets/27becc9e-2699-43af-bf08-66e33843ad19" />

**Comment by m3svcs** [comment]
@prd-hoang-doan, thank you for your prompt reply.

I set up the PostMan like this:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0cc344d4-7e3c-4939-8866-56a074f6ecdd" />

For the body, I selected the entire Request text in a text file.txt like this:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/56c3da50-d748-4a98-b626-7f3b140a2f76" />

Thank you very much.

m3svcs

**Comment by m3svcs** [comment]
@prd-hoang-doan, changing to `text/plain`,  I got back the same error in my first post:

`{"statusCode":500,"success":false,"message":"Error: documentStoreServices.upsertDocStoreMiddleware - Error: documentStoreServices.upsertDocStore - Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":{}}`

The loader data is amended and the File_Chunks are inserted into Postgres tables but document and upsert_records are not updated in the Postgres tables.

Thank you very much.

m3svcs

**Comment by prd-hoang-doan** [comment]
@m3svcs Thank you for providing your context how you integrate with Flowise API.
I found that you're using wrong the content-type in Body tab (Postman). You should change from "binary" to "form-data".
Then filling all necessary fields under the format key-value.

<img width="2259" height="827" alt="Image" src="https://github.com/user-attachments/assets/6aacb681-e534-498e-86d1-fc2f6ddf3550" />

I recommend you should use Flowise UI for insert the document store, then call the API via Postman for upsert. 

<img width="1237" height="508" alt="Image" src="https://github.com/user-attachments/assets/fbaaddde-2251-47a6-a61a-5f1307c1ea63" />

The Flowise API accepted the your file, but it need credentials (username, password) for vector database. But your request doesn't include this, so it raises the error below:
```
{"statusCode":500,"success":false,"message":"Error: documentStoreServices.upsertDocStoreMiddleware - Error: documentStoreServices.upsertDocStore - Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":{}}
```
If you still stuck at this point, I will record video to support you in the future.

**Comment by m3svcs** [comment]
@prd-hoang-doan, thank you for your help.  I thought connectionCredentials already has the password stored/captured in the system, is there an alternative way to specify explicitly the password instead of relying on the connectionCredentials for the password?

------WebKitFormBoundaryAIisForAllWhoIuvaAI
Content-Disposition: form-data; name="vectorStore"
Content-Type: application/json

{ "name": "postgres", "config": { **"connectCredentials": "Postgres"**, "host": "localhost", "database": "flowise", "port": 5432, "tableName": "documents", "distanceStrategy": "Cosine", "topK": 4, "contentColumnName": "pageContent" } }
------WebKitFormBoundaryAIisForAllWhoIuvaAI

Thank you very much.

m3svcs

**Comment by prd-hoang-doan** [comment]
@m3svcs Currently the system relies on `connectionCredentials`, there is no way to pass username/password for the vector database during upsert API. In this case, I suggest you create the document store and first insert via Flowise UI, then use the upsert API to replace the file while using the same config for `vectorStore`, `recordManager`

**Comment by m3svcs** [comment]
@prd-hoang-doan, if the Upsert API in 3.1.0 is still not ready now, is there a timeline for a working API version to be released?

I'm thinking of reverting to 3.0.5 when the API was working in 2025.  As I have 400,000+ docs to upsert, using the Flowise GUI to upsert is not possible.

Thank you very much.

m3svcs

**Comment by m3svcs** [comment]
@prd-hoang-doan, thanks for 3.1.1, although Upsert API still doesn't update upsert_records and document tables, but delete_doc_loader_and_chunks API is working again.   Hope the Upsert API bug will be solved soon.

Thank you very much.

m3svcs

**Comment by prd-hoang-doan** [comment]
@m3svcs It's great to hear that. Could you share your real-case steps of using upsert API? (for example, what's the client call the API). I need reproduce steps to determine whether the API is buggy or not.

**Comment by mittayrmalak-boop** [comment]
Thanks for the feedback and for testing version 3.1.1.

**Comment by m3svcs** [comment]
@prd-hoang-doan, I'm using vb6 and XML call to the endpoint.  Applying the exact same _text content_ for the payload I used in my previous example, I can still use Postman to simulate my client call.  You can use Postman too.  I'd hope to not revert to 3.0.5.

Thank you very much.

m3svcs

**Comment by m3svcs** [comment]
@prd-hoang-doan, thanks for 3.1.2, but it still didn't help me.  Upsert API still doesn't update upsert_records and document tables, but delete_doc_loader_and_chunks API is working again. Hope the Upsert API bug will be solved soon.

Thank you very much.

m3svcs
